# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
permissions:
  contents: read
  packages: write
  id-token: write

name: Secure-ci-cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    defaults:
      run:
       working-directory: ./app
       
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Build
      run: go build -v ./...
      
    # Run tests
    - name: Test
      run: go test -v ./...

    - name: Run Go vet
      run: go vet ./...

    - name: Check Formatting
      run: test -z "$(gofmt -l .)"
      
    # Run lint on the application
    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        skip-cache: true
        working-directory: ./app

    # Run security Scans; Gitleaks to check for secrets, trivy for container image and dependency/ filesystem scanning
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    # Filesystem scan
    - name: Trivy FS Scan
      uses: aquasecurity/trivy-action@v0.35.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'

    # Log into Container Registry
    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
    # Build image stage
    - name: Generate Image Tag
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
    
        IMAGE_TAG="${SHORT_SHA}-${TIMESTAMP}"
    
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "IMAGE_NAME=ghcr.io/jed212/secure-go-api:$IMAGE_TAG" >> $GITHUB_ENV
        
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME .
      working-directory: .


    # Docker Image scan configured to fail for Critical and High severity vulnerabilities
    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@0.35.0
      with:
        image-ref: ${{ env.IMAGE_NAME }}
        severity: 'CRITICAL,HIGH'
        exit-code: '1'

    # Generate and publish SBOM
    - name: Generate SBOM
      uses: aquasecurity/trivy-action@0.35.0
      with:
        image-ref: ${{ env.IMAGE_NAME }}
        format: 'cyclonedx'
        output: 'sbom.json'

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: sbom.json
        
    # Push to ghcr
    - name: Push Image
      run: docker push ${{ env.IMAGE_NAME }}
      working-directory: .

    # # Get the image digest and use to sign image
    # - name: Get Image Digest
    #   run: |
    #     DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/${{ github.repository }}/secure-go-api:1.0)
    #     echo "IMAGE=$DIGEST" >> $GITHUB_ENV
        
    # # Install Cosign
    # - name: Install Cosign
    #   uses: sigstore/cosign-installer@v4.1.1
    
    # # Sign Image
    # - name: Sign Image
    #   env:
    #     COSIGN_EXPERIMENTAL: "true"
    #   run: |
    #     cosign sign --yes $IMAGE_NAME
    
    # Use ssh instead of https (to be optimized later)
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITOPS_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # Update GitOps repo with new image
    - name: Update GitOps Repo (CD Trigger)
      env:
        IMAGE: ${{ env.IMAGE_NAME }}
        GITOPS_REPO: git@github.com:jed212/gitops-lab.git
      working-directory: .
      run: |
        set -e
    
        echo "Cloning GitOps repo..."
        git clone $GITOPS_REPO gitops
    
        cd gitops
    
        echo "Updating image in deployment..."
        sed -i "s|image: .*|image: $IMAGE|" apps/secure-go-api/deployment.yaml
    
        echo "Configuring git..."
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
    
        echo "Committing changes..."
        git add .
        git commit -m "Update image to $IMAGE" || echo "No changes to commit"
    
        echo "Pushing changes..."
        git push
