# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
permissions:
  contents: read
  packages: write

name: Secure-ci-cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    defaults:
      run:
       working-directory: ./secure-gitops-platform/app
       
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Build
      run: go build -v ./...
      
    # Run tests
    - name: Test
      run: go test -v ./...

    - name: Run Go vet
      run: go vet ./...

    - name: Check Formatting
      run: test -z "$(gofmt -l .)"
      
    # Run lint on the application
    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        skip-cache: true
        working-directory: ./secure-gitops-platform/app

    # Run security Scans; Gitleaks to check for secrets, trivy for container image and dependency/ filesystem scanning
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      
    # Filesystem scan
    - name: Trivy FS Scan
      uses: aquasecurity/trivy-action@v0.35.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'

    # Log into Container Registry
    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
    # Build image stage
    - name: Build Docker Image
      run: docker build -t ghcr.io/${{ github.repository }}/secure-go-api:1.0 .
      working-directory: ./secure-gitops-platform

    # Docker Image scan configured to fail for Critical and High severity vulnerabilities
    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@0.35.0
      with:
        image-ref: 'ghcr.io/${{ github.repository }}/secure-go-api:1.0'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'

    # Generate and publish SBOM
    - name: Generate SBOM
      uses: aquasecurity/trivy-action@0.35.0
      with:
        image-ref: 'ghcr.io/${{ github.repository }}/secure-go-api:1.0'
        format: 'cyclonedx'
        output: 'sbom.json'

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: sbom.json
        
    # Push to ghcr
    - name: Push Image
      run: docker push ghcr.io/${{ github.repository }}/secure-go-api:1.0

    # Get the image digest and use to sign image
    - name: Get Image Digest
      run: |
        DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/${{ github.repository }}/secure-go-api:1.0)
        echo "IMAGE=$DIGEST" >> $GITHUB_ENV
        
    # Install Cosign
    - name: Install Cosign
      uses: sigstore/cosign-installer@v4.1.1
    
    # Sign Image
    - name: Sign Image
      run: |
          cosign sign --yes $IMAGE
